export default {
  LOGIN_USER: 'LOGIN_USER',
  SIGNOUT_USER: 'SIGNOUT_USER',
  SET_DRAFT_AP: 'SET_DRAFT_AP',
  ADD_FCE: 'ADD_FCE',
  REMOVE_FCE: 'REMOVE_FCE',
  SET_CURRENT_FCE: 'SET_CURRENT_FCE',
};
